
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:5000/CUSTOMER
    username: root
    password: pwd
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximumPoolSize: 10
      idleTimeout: 120000
      minimumIdle: 5
      maxLifetime: 120000

  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQL5Dialect
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: mysql
    show-sql: true
    open-in-view: false